# Generated by Django 3.0.8 on 2020-07-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ItemQTY',
        ),
        migrations.RemoveField(
            model_name='report',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='price',
        ),
        migrations.RemoveField(
            model_name='report',
            name='stock',
        ),
        migrations.AddField(
            model_name='report',
            name='Formatted_ID',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='report',
            name='Name',
            field=models.CharField(default='null', max_length=2083),
        ),
        migrations.AddField(
            model_name='report',
            name='Priority',
            field=models.CharField(default='null', max_length=2083),
        ),
        migrations.AddField(
            model_name='report',
            name='Severity',
            field=models.CharField(default='null', max_length=2083),
        ),
        migrations.AddField(
            model_name='report',
            name='State',
            field=models.CharField(default='null', max_length=2083),
        ),
        migrations.AddField(
            model_name='report',
            name='Submitted_By',
            field=models.CharField(default='null', max_length=2083),
        ),
    ]
