# Generated by Django 3.0.8 on 2020-07-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0002_auto_20200711_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='Formatted_ID',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Submitted_By',
        ),
    ]
