# Generated by Django 3.0.8 on 2020-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0003_auto_20200712_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='router_specifications')),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='Name',
            field=models.CharField(max_length=2083),
        ),
    ]
