# Generated by Django 3.0.8 on 2020-07-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0005_auto_20200713_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='QALabSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='null', max_length=2083)),
                ('Priority', models.CharField(default='null', max_length=2083)),
                ('State', models.CharField(default='null', max_length=2083)),
                ('Attachements', models.FileField(default='null', upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
