# Generated by Django 3.0.8 on 2020-07-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0007_smartterminaldefects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartTerminalDefects',
            new_name='SmartTerminalDefect',
        ),
    ]
