# Generated by Django 3.0.8 on 2020-07-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0009_launchpaddefects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launchpaddefects',
            old_name='Defect_Attachements',
            new_name='LAttachements',
        ),
        migrations.RenameField(
            model_name='launchpaddefects',
            old_name='Defect_Name',
            new_name='LName',
        ),
        migrations.RenameField(
            model_name='launchpaddefects',
            old_name='Defect_Priority',
            new_name='LPriority',
        ),
        migrations.RenameField(
            model_name='launchpaddefects',
            old_name='Defect_Severity',
            new_name='LSeverity',
        ),
        migrations.RenameField(
            model_name='launchpaddefects',
            old_name='Defect_State',
            new_name='LState',
        ),
        migrations.RenameField(
            model_name='smartterminaldefect',
            old_name='Defect_Attachements',
            new_name='DAttachements',
        ),
        migrations.RenameField(
            model_name='smartterminaldefect',
            old_name='Defect_Name',
            new_name='DName',
        ),
        migrations.RenameField(
            model_name='smartterminaldefect',
            old_name='Defect_Priority',
            new_name='DPriority',
        ),
        migrations.RenameField(
            model_name='smartterminaldefect',
            old_name='Defect_Severity',
            new_name='DSeverity',
        ),
        migrations.RenameField(
            model_name='smartterminaldefect',
            old_name='Defect_State',
            new_name='DState',
        ),
    ]
