# Generated by Django 3.0.8 on 2020-07-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0010_auto_20200714_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
