# Generated by Django 3.0.8 on 2020-07-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingApp', '0011_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='LName',
            field=models.CharField(default='null', max_length=2083),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='LPriority',
            field=models.CharField(default='null', max_length=2083),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='LSeverity',
            field=models.CharField(default='null', max_length=2083),
        ),
    ]
